# Generated by Django 3.1.4 on 2021-04-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prod_img',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
