# Generated by Django 3.1.4 on 2021-04-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210403_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prod_img',
            field=models.ImageField(default='default_thumbnail.png', upload_to='Product_images'),
        ),
    ]
