# Generated by Django 3.1.7 on 2021-04-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210403_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('books', 'books'), ('notes', 'notes'), ('lab_equipments', 'lab_equipments'), ('electronic_equipments', 'electronic_equipments'), ('sports_equipments', 'sports_equipments'), ('appliances', 'appliances'), ('miscellenous', 'miscellenous')], default='miscellenous', max_length=30),
        ),
    ]
