# Generated by Django 3.1.7 on 2021-04-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('books', 'Books'), ('notes', 'Reference Notes'), ('lab_equipments', 'Lab Equipments'), ('electronic_equipments', 'Electronic Equipments'), ('sports_equipments', 'Sports Equipments'), ('appliances', 'Appliances'), ('miscellenous', 'Miscellenous')], default='miscellenous', max_length=30),
        ),
    ]
