# Generated by Django 3.1.7 on 2021-04-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210403_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Reference Notes', 'Reference Notes'), ('Lab Equipments', 'Lab Equipments'), ('Electronic Equipments', 'Electronic Equipments'), ('Sports Equipments', 'Sports Equipments'), ('Appliances', 'Appliances'), ('Miscellenous', 'Miscellenous')], default='Miscellenous', max_length=30),
        ),
    ]
