# Generated by Django 3.1.6 on 2021-04-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='content',
        ),
    ]
